services:
  grafana:
    user: root
    container_name: jaegertracing-grafana
    build:
      context: packages/panel/.config
      dockerfile: Dockerfile
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-12.4.0}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./packages/panel/dist:/var/lib/grafana/plugins/jaegertracing-jaeger-panel
      - ./packages/datasource/dist:/var/lib/grafana/plugins/jaegertracing-jaeger-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      NODE_ENV: development
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: jaegertracing-jaeger-panel,jaegertracing-jaeger-datasource

  jaeger:
    image: jaegertracing/jaeger:2.18.0@sha256:d2cbd047e44b50c11454820f84fd5f34c24a435e5301cf94fe026bf055db80b3
    container_name: jaegertracing-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  hotrod:
    image: jaegertracing/example-hotrod:2.18.0@sha256:61627c2d827bae3ba2e09c90c447272f3e642fe6eadc2f1fca6b542d45a9ea56
    container_name: jaegertracing-hotrod
    ports:
      - "8080:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    depends_on:
      - jaeger
